### ISSUE TITLE
Some commands still leave empty space

### ISSUE THREAD

**Issue by TristanWiley** [TristanWiley/So-Chat-Commander#13]
Some command still leave empty space (and enter/new line) after entering the command.

**Comment by jonathanGB** [comment]
Do you know which commands in particular?

**Comment by TristanWiley** [comment]
Looks like /dice and /coin are two, not sure what else. There's a delay on some which is okay, could be possibly fixed.

**Comment by jonathanGB** [comment]
I'm gonna go through your code today, see if I can help. Also, I have found some optimizations that are not related to this issue that you could pull of.

**Comment by TristanWiley** [comment]
Okay :+1:

**Comment by jonathanGB** [comment]
Humm, never used SO chat before. How can I test changes?

**Comment by TristanWiley** [comment]
Go onto chat.stackoverflow.com, room 1 is a Sandbox room to test
https://chat.stackoverflow.com/rooms/1

**Comment by jonathanGB** [comment]
I have found a simple way to fix this, I'll wait for you to accept/reject my previous PR ( #21 ) before proposing a new PR to fix the current issue!

**Comment by jonathanGB** [comment]
See #21

**Comment by TristanWiley** [comment]
:+1:
