### ISSUE TITLE
Better icon? Do we need one? Input?

### ISSUE THREAD

**Issue by TristanWiley** [TristanWiley/So-Chat-Commander#16]
I made the icon with some icon creator a while back, now that it's getting more serious and we have users... Does someone want to make a nicer one? Do we need one?

**Comment by revolter** [comment]
Do you need it to looks similar to the current one?

**Comment by TristanWiley** [comment]
Nope, if it's good and I like it I'll accept the PR.

**Comment by raj-maurya** [comment]
Hi @TristanWiley 

The current version of icon is good, And I can modify it a little bit for some enhancement.

**Comment by TristanWiley** [comment]
Thanks for your feedback! If you want to modify it you're welcome to and I'll judge it and possible accept it! :)
