### ISSUE TITLE
Skeet API not responding anymore

### ISSUE THREAD

**Issue by jonathanGB** [TristanWiley/So-Chat-Commander#22]
@TristanWiley, you should look into that. I think we've reached the limit of the API.

![image](https://cloud.githubusercontent.com/assets/8869660/19023462/c7ffa3f8-88bc-11e6-947a-3727cf4ade9b.png)

**Comment by TristanWiley** [comment]
That's my fault, I'm hosting it on my personal website host and forgot to renew it. Give me a bit.

**Comment by TristanWiley** [comment]
Fixed, paid my money. I want to start a Slack so I can thank everyone who's helping :D. I'll do it later

**Comment by jonathanGB** [comment]
Alright haha, otherwise a gitter?

**Comment by TristanWiley** [comment]
Hey @jonathanGB and @drobilc what are emails I should invite you to a Slack with?

**Comment by jonathanGB** [comment]
jonathan.guillotte.blouin@gmail.com

**Comment by drobilc** [comment]
drobilc@gmail.com
