### ISSUE TITLE
Change all OneBoxed Youtube videos to embed.

### ISSUE THREAD

**Issue by TristanWiley** [TristanWiley/So-Chat-Commander#36]
So as of now Stackoverflow takes Youtube links and basically makes a linked image to the video. 

What this feature should do is instead of the current code of an image with a link, we should have the embed code with the same size.

This is the current HTML

```
<div class="onebox ob-youtube">
   <a rel="nofollow noopener noreferrer" style="text-decoration: none;" href="https://www.youtube.com/watch?v=KgmO32IdwuE">
      <img src="http://i2.ytimg.com/vi/KgmO32IdwuE/hqdefault.jpg" width="240" height="180" class="ob-youtube-preview">
      <div class="ob-youtube-title">Taken phone scene</div>
      <div class="ob-youtube-overlay">►</div>
   </a>
</div>
```

what it should be is something the same size except with the video's embed code.

**Comment by alinarezrangel** [comment]
Hi @TristanWiley, I can help you in this task.

**Comment by TristanWiley** [comment]
Awesome @alinarezrangel!

**Comment by alinarezrangel** [comment]
I have one question: in most of the Google Chrome apps, a HTML file contains the main layout of the page and the view, but in this app I was unable to search that file. Is the used file external or something like that?

**Comment by TristanWiley** [comment]
There's no HTML file here, it's just JS.

**Comment by alinarezrangel** [comment]
Ok, thanks

**Comment by alinarezrangel** [comment]
Hi, I have a problem: I installed the extension from the chrome webstore (I wanna try it before develop the feature) but when I click the icon in the address bar, nothing happens.

**Comment by TristanWiley** [comment]
The icon doesn't do anything, the script automatically runs on the chat page.

**Comment by MinerBigWhale** [comment]
Don't know when do you want to trigger that function so I let you decide ^^

**Comment by TristanWiley** [comment]
Awesome @MinerBigWhale, I'll check it out when I get home. I was thinking for it to automatically do it. Always.

**Comment by MinerBigWhale** [comment]
Do you think there is a way to get an event when a new message is recieved ?

**Comment by TristanWiley** [comment]
Yep, but it's complicated. You have to listen to the websocket connection I think. @drobilc do you know?

**Comment by drobilc** [comment]
Umm, not really.

**Comment by TristanWiley** [comment]
@MinerBigWhale courtesy of my friend, might need to be changed a bit.

```
new MutationOberver( records => {
    records.forEach( record => Array.from(record.addedNodes).forEach(parseNode) );
}).observe(chat, { childList: true, subtree: true });

function parseNode(node) {
    if( !node.classList || !node.classList.contains('message') || node.classList.contains('pending') ) return;
    // process new message
}
```

**Comment by rlemon** [comment]
https://gist.github.com/rlemon/7914903 you can probably borrow quite a bit from here.

**Comment by rlemon** [comment]
```
const chat = document.getElementById('chat');
// get all existing messages
Array.from(chat.querySelectorAll('.user-container .message')).forEach(parseNode);
// get new messages
new MutationObserver( records => {
    records.forEach( record => Array.from(record.addedNodes).forEach(parseNode) );
}).observe(chat, { childList: true, subtree: true });
// node parser
function parseNode(node) {
    if( !node.classList || !node.classList.contains('message') || node.classList.contains('pending') ) return; // if not message node, exit
    const ty = node.querySelector('.onebox.ob-youtube'); // grab youtube onebox
    if( !ty ) return; // exit if not found
    const link = ty.querySelector('a'); // youtube link address
    const videoHref = link.href.match(/v\=(.*)&?/).pop().replace(/&/, '/?'); // ^
    const vid = document.createElement('iframe'); // new vidja element
    vid.setAttribute('height', 240); // setting attributes ... properties would also work.
    vid.setAttribute('width', 320);
    vid.setAttribute('frameborder', 0);
    vid.setAttribute('allowfullscreen', 'true');
    vid.src = '//youtube.com/embed/' + videoHref; // new href
    ty.parentNode.replaceChild(vid, ty); // replace old link with iframe
}
```

this works fine, but I'm not sure how your coding styles are in this repo. If you'd like a PR ping me on SO chat -- FWIW I will probably add this to Dark Theme, I was under the assumption it was there (I had another userscript doing this on my machine).
