### ISSUE TITLE
Default fall through to send messages that start with slash

### ISSUE THREAD

**Issue by AdamMc331** [TristanWiley/So-Chat-Commander#55]
If I enter a message like "//somebotcommand" it doesn't show up because I believe it's being intercepted by this chrome extension.

It would be nice to add a default fall through that, if the message started with a slash but wasn't one of the known commands, it would proceed and send as expected.

**Comment by TristanWiley** [comment]
Adam are you gonna do this or just say you will and never do it? <3

**Comment by AdamMc331** [comment]
Nah, I actually commit to side projects I say I'm gonna do.
