### ISSUE TITLE
Add a settings page

### ISSUE THREAD

**Issue by TristanWiley** [TristanWiley/So-Chat-Commander#7]
Add a settings page that allows you to pick and choose what commands you use and other things you can think of.

**Comment by drobilc** [comment]
I'm going to work on this today, I'll add options to manually enable or disable commands, make them non-case-sensitive, maybe even allow users to add new commands.

**Comment by TristanWiley** [comment]
Awesome :+1:

**Comment by TristanWiley** [comment]
@drobilc Any update?

**Comment by drobilc** [comment]
@TristanWiley sorry, didn't have time, I'm going to finish it this week :)

**Comment by TristanWiley** [comment]
@drobilc no worries :)
